### Get commodity response
GET {{mdmStubUrl}}/mdm/api?filter=commodity&effectiveFrom=2012-10-01T09:45:00Z&effectiveTo=2012-10-02T09:45:00Z
Ocp-Apim-Subscription-Key: {{apiManagementSubScriptionKey}}

### Get commodity code response
GET {{mdmStubUrl}}/mdm/api?filter=commodity_code&effectiveFrom=2012-10-01T09:45:00Z&effectiveTo=2012-10-02T09:45:00Z
Ocp-Apim-Subscription-Key: {{apiManagementSubScriptionKey}}

### Get species response
GET {{mdmStubUrl}}/mdm/api?filter=tulips&effectiveFrom=2012-10-01T09:45:00Z&effectiveTo=2012-10-02T09:45:00Z
Ocp-Apim-Subscription-Key: {{apiManagementSubScriptionKey}}